// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos.proto

package yang.shuai.ysservice.domain;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserCacheOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.UserCache)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>uint32 UID = 1;</code>
     */
    int getUID();

    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    String getName();
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 头像id
     * </pre>
     *
     * <code>int32 Head = 3;</code>
     */
    int getHead();

    /**
     * <pre>
     * 玩家VIP等级
     * </pre>
     *
     * <code>int32 VIP = 4;</code>
     */
    int getVIP();
  }
  /**
   * Protobuf type {@code protos.UserCache}
   */
  public  static final class UserCache extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.UserCache)
      UserCacheOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserCache.newBuilder() to construct.
    private UserCache(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserCache() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserCache();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserCache(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uID_ = input.readUInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              head_ = input.readInt32();
              break;
            }
            case 32: {

              vIP_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protos.internal_static_protos_UserCache_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protos.internal_static_protos_UserCache_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protos.UserCache.class, Protos.UserCache.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uID_;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>uint32 UID = 1;</code>
     */
    public int getUID() {
      return uID_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 昵称
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_FIELD_NUMBER = 3;
    private int head_;
    /**
     * <pre>
     * 头像id
     * </pre>
     *
     * <code>int32 Head = 3;</code>
     */
    public int getHead() {
      return head_;
    }

    public static final int VIP_FIELD_NUMBER = 4;
    private int vIP_;
    /**
     * <pre>
     * 玩家VIP等级
     * </pre>
     *
     * <code>int32 VIP = 4;</code>
     */
    public int getVIP() {
      return vIP_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uID_ != 0) {
        output.writeUInt32(1, uID_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (head_ != 0) {
        output.writeInt32(3, head_);
      }
      if (vIP_ != 0) {
        output.writeInt32(4, vIP_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uID_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (head_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, head_);
      }
      if (vIP_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, vIP_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protos.UserCache)) {
        return super.equals(obj);
      }
      Protos.UserCache other = (Protos.UserCache) obj;

      if (getUID()
          != other.getUID()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getHead()
          != other.getHead()) return false;
      if (getVIP()
          != other.getVIP()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUID();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHead();
      hash = (37 * hash) + VIP_FIELD_NUMBER;
      hash = (53 * hash) + getVIP();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protos.UserCache parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.UserCache parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.UserCache parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.UserCache parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.UserCache parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.UserCache parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.UserCache parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.UserCache parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.UserCache parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protos.UserCache parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.UserCache parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.UserCache parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protos.UserCache prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.UserCache}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.UserCache)
        Protos.UserCacheOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protos.internal_static_protos_UserCache_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protos.internal_static_protos_UserCache_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protos.UserCache.class, Protos.UserCache.Builder.class);
      }

      // Construct using yang.shuai.ys_blog_service.domain.Protos.UserCache.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        uID_ = 0;

        name_ = "";

        head_ = 0;

        vIP_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protos.internal_static_protos_UserCache_descriptor;
      }

      @Override
      public Protos.UserCache getDefaultInstanceForType() {
        return Protos.UserCache.getDefaultInstance();
      }

      @Override
      public Protos.UserCache build() {
        Protos.UserCache result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Protos.UserCache buildPartial() {
        Protos.UserCache result = new Protos.UserCache(this);
        result.uID_ = uID_;
        result.name_ = name_;
        result.head_ = head_;
        result.vIP_ = vIP_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protos.UserCache) {
          return mergeFrom((Protos.UserCache)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protos.UserCache other) {
        if (other == Protos.UserCache.getDefaultInstance()) return this;
        if (other.getUID() != 0) {
          setUID(other.getUID());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHead() != 0) {
          setHead(other.getHead());
        }
        if (other.getVIP() != 0) {
          setVIP(other.getVIP());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protos.UserCache parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protos.UserCache) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uID_ ;
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>uint32 UID = 1;</code>
       */
      public int getUID() {
        return uID_;
      }
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>uint32 UID = 1;</code>
       */
      public Builder setUID(int value) {

        uID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>uint32 UID = 1;</code>
       */
      public Builder clearUID() {

        uID_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 昵称
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private int head_ ;
      /**
       * <pre>
       * 头像id
       * </pre>
       *
       * <code>int32 Head = 3;</code>
       */
      public int getHead() {
        return head_;
      }
      /**
       * <pre>
       * 头像id
       * </pre>
       *
       * <code>int32 Head = 3;</code>
       */
      public Builder setHead(int value) {

        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像id
       * </pre>
       *
       * <code>int32 Head = 3;</code>
       */
      public Builder clearHead() {

        head_ = 0;
        onChanged();
        return this;
      }

      private int vIP_ ;
      /**
       * <pre>
       * 玩家VIP等级
       * </pre>
       *
       * <code>int32 VIP = 4;</code>
       */
      public int getVIP() {
        return vIP_;
      }
      /**
       * <pre>
       * 玩家VIP等级
       * </pre>
       *
       * <code>int32 VIP = 4;</code>
       */
      public Builder setVIP(int value) {

        vIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家VIP等级
       * </pre>
       *
       * <code>int32 VIP = 4;</code>
       */
      public Builder clearVIP() {

        vIP_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.UserCache)
    }

    // @@protoc_insertion_point(class_scope:protos.UserCache)
    private static final Protos.UserCache DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protos.UserCache();
    }

    public static Protos.UserCache getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserCache>
        PARSER = new com.google.protobuf.AbstractParser<UserCache>() {
      @Override
      public UserCache parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserCache(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserCache> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserCache> getParserForType() {
      return PARSER;
    }

    @Override
    public Protos.UserCache getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.Resource)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 资源类型
     * </pre>
     *
     * <code>int32 Type = 1;</code>
     */
    int getType();

    /**
     * <pre>
     * 资源数量
     * </pre>
     *
     * <code>uint32 Num = 2;</code>
     */
    int getNum();
  }
  /**
   * Protobuf type {@code protos.Resource}
   */
  public  static final class Resource extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.Resource)
      ResourceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Resource.newBuilder() to construct.
    private Resource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Resource() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Resource();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Resource(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              num_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protos.internal_static_protos_Resource_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protos.internal_static_protos_Resource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protos.Resource.class, Protos.Resource.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 资源类型
     * </pre>
     *
     * <code>int32 Type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <pre>
     * 资源数量
     * </pre>
     *
     * <code>uint32 Num = 2;</code>
     */
    public int getNum() {
      return num_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (num_ != 0) {
        output.writeUInt32(2, num_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, num_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protos.Resource)) {
        return super.equals(obj);
      }
      Protos.Resource other = (Protos.Resource) obj;

      if (getType()
          != other.getType()) return false;
      if (getNum()
          != other.getNum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protos.Resource parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Resource parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Resource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Resource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Resource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Resource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Resource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.Resource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.Resource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protos.Resource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.Resource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.Resource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protos.Resource prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.Resource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.Resource)
        Protos.ResourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protos.internal_static_protos_Resource_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protos.internal_static_protos_Resource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protos.Resource.class, Protos.Resource.Builder.class);
      }

      // Construct using yang.shuai.ys_blog_service.domain.Protos.Resource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        num_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protos.internal_static_protos_Resource_descriptor;
      }

      @Override
      public Protos.Resource getDefaultInstanceForType() {
        return Protos.Resource.getDefaultInstance();
      }

      @Override
      public Protos.Resource build() {
        Protos.Resource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Protos.Resource buildPartial() {
        Protos.Resource result = new Protos.Resource(this);
        result.type_ = type_;
        result.num_ = num_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protos.Resource) {
          return mergeFrom((Protos.Resource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protos.Resource other) {
        if (other == Protos.Resource.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protos.Resource parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protos.Resource) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 资源类型
       * </pre>
       *
       * <code>int32 Type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 资源类型
       * </pre>
       *
       * <code>int32 Type = 1;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 资源类型
       * </pre>
       *
       * <code>int32 Type = 1;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <pre>
       * 资源数量
       * </pre>
       *
       * <code>uint32 Num = 2;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <pre>
       * 资源数量
       * </pre>
       *
       * <code>uint32 Num = 2;</code>
       */
      public Builder setNum(int value) {

        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 资源数量
       * </pre>
       *
       * <code>uint32 Num = 2;</code>
       */
      public Builder clearNum() {

        num_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.Resource)
    }

    // @@protoc_insertion_point(class_scope:protos.Resource)
    private static final Protos.Resource DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protos.Resource();
    }

    public static Protos.Resource getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Resource>
        PARSER = new com.google.protobuf.AbstractParser<Resource>() {
      @Override
      public Resource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Resource(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Resource> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Resource> getParserForType() {
      return PARSER;
    }

    @Override
    public Protos.Resource getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResourcesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.Resources)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    java.util.List<Resource>
        getAddList();
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    Protos.Resource getAdd(int index);
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    int getAddCount();
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    java.util.List<? extends ResourceOrBuilder>
        getAddOrBuilderList();
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    Protos.ResourceOrBuilder getAddOrBuilder(
            int index);

    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    java.util.List<Resource>
        getDelList();
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    Protos.Resource getDel(int index);
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    int getDelCount();
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    java.util.List<? extends ResourceOrBuilder>
        getDelOrBuilderList();
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    Protos.ResourceOrBuilder getDelOrBuilder(
            int index);

    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    java.util.List<Resource>
        getAllList();
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    Protos.Resource getAll(int index);
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    int getAllCount();
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    java.util.List<? extends ResourceOrBuilder>
        getAllOrBuilderList();
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    Protos.ResourceOrBuilder getAllOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code protos.Resources}
   */
  public  static final class Resources extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.Resources)
      ResourcesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Resources.newBuilder() to construct.
    private Resources(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Resources() {
      add_ = java.util.Collections.emptyList();
      del_ = java.util.Collections.emptyList();
      all_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Resources();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Resources(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                add_ = new java.util.ArrayList<Resource>();
                mutable_bitField0_ |= 0x00000001;
              }
              add_.add(
                  input.readMessage(Protos.Resource.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                del_ = new java.util.ArrayList<Resource>();
                mutable_bitField0_ |= 0x00000002;
              }
              del_.add(
                  input.readMessage(Protos.Resource.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                all_ = new java.util.ArrayList<Resource>();
                mutable_bitField0_ |= 0x00000004;
              }
              all_.add(
                  input.readMessage(Protos.Resource.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          add_ = java.util.Collections.unmodifiableList(add_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          del_ = java.util.Collections.unmodifiableList(del_);
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          all_ = java.util.Collections.unmodifiableList(all_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protos.internal_static_protos_Resources_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protos.internal_static_protos_Resources_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protos.Resources.class, Protos.Resources.Builder.class);
    }

    public static final int ADD_FIELD_NUMBER = 1;
    private java.util.List<Resource> add_;
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    public java.util.List<Resource> getAddList() {
      return add_;
    }
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    public java.util.List<? extends ResourceOrBuilder>
        getAddOrBuilderList() {
      return add_;
    }
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    public int getAddCount() {
      return add_.size();
    }
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    public Protos.Resource getAdd(int index) {
      return add_.get(index);
    }
    /**
     * <pre>
     * 添加的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Add = 1;</code>
     */
    public Protos.ResourceOrBuilder getAddOrBuilder(
        int index) {
      return add_.get(index);
    }

    public static final int DEL_FIELD_NUMBER = 2;
    private java.util.List<Resource> del_;
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    public java.util.List<Resource> getDelList() {
      return del_;
    }
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    public java.util.List<? extends ResourceOrBuilder>
        getDelOrBuilderList() {
      return del_;
    }
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    public int getDelCount() {
      return del_.size();
    }
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    public Protos.Resource getDel(int index) {
      return del_.get(index);
    }
    /**
     * <pre>
     * 减少的资源
     * </pre>
     *
     * <code>repeated .protos.Resource Del = 2;</code>
     */
    public Protos.ResourceOrBuilder getDelOrBuilder(
        int index) {
      return del_.get(index);
    }

    public static final int ALL_FIELD_NUMBER = 3;
    private java.util.List<Resource> all_;
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    public java.util.List<Resource> getAllList() {
      return all_;
    }
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    public java.util.List<? extends ResourceOrBuilder>
        getAllOrBuilderList() {
      return all_;
    }
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    public int getAllCount() {
      return all_.size();
    }
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    public Protos.Resource getAll(int index) {
      return all_.get(index);
    }
    /**
     * <pre>
     * 总的资源
     * </pre>
     *
     * <code>repeated .protos.Resource All = 3;</code>
     */
    public Protos.ResourceOrBuilder getAllOrBuilder(
        int index) {
      return all_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < add_.size(); i++) {
        output.writeMessage(1, add_.get(i));
      }
      for (int i = 0; i < del_.size(); i++) {
        output.writeMessage(2, del_.get(i));
      }
      for (int i = 0; i < all_.size(); i++) {
        output.writeMessage(3, all_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < add_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, add_.get(i));
      }
      for (int i = 0; i < del_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, del_.get(i));
      }
      for (int i = 0; i < all_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, all_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protos.Resources)) {
        return super.equals(obj);
      }
      Protos.Resources other = (Protos.Resources) obj;

      if (!getAddList()
          .equals(other.getAddList())) return false;
      if (!getDelList()
          .equals(other.getDelList())) return false;
      if (!getAllList()
          .equals(other.getAllList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAddCount() > 0) {
        hash = (37 * hash) + ADD_FIELD_NUMBER;
        hash = (53 * hash) + getAddList().hashCode();
      }
      if (getDelCount() > 0) {
        hash = (37 * hash) + DEL_FIELD_NUMBER;
        hash = (53 * hash) + getDelList().hashCode();
      }
      if (getAllCount() > 0) {
        hash = (37 * hash) + ALL_FIELD_NUMBER;
        hash = (53 * hash) + getAllList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protos.Resources parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Resources parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Resources parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Resources parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Resources parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protos.Resources parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protos.Resources parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.Resources parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.Resources parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protos.Resources parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protos.Resources parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protos.Resources parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protos.Resources prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.Resources}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.Resources)
        Protos.ResourcesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protos.internal_static_protos_Resources_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protos.internal_static_protos_Resources_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protos.Resources.class, Protos.Resources.Builder.class);
      }

      // Construct using yang.shuai.ys_blog_service.domain.Protos.Resources.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddFieldBuilder();
          getDelFieldBuilder();
          getAllFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (addBuilder_ == null) {
          add_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          addBuilder_.clear();
        }
        if (delBuilder_ == null) {
          del_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          delBuilder_.clear();
        }
        if (allBuilder_ == null) {
          all_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          allBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protos.internal_static_protos_Resources_descriptor;
      }

      @Override
      public Protos.Resources getDefaultInstanceForType() {
        return Protos.Resources.getDefaultInstance();
      }

      @Override
      public Protos.Resources build() {
        Protos.Resources result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Protos.Resources buildPartial() {
        Protos.Resources result = new Protos.Resources(this);
        int from_bitField0_ = bitField0_;
        if (addBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            add_ = java.util.Collections.unmodifiableList(add_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.add_ = add_;
        } else {
          result.add_ = addBuilder_.build();
        }
        if (delBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            del_ = java.util.Collections.unmodifiableList(del_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.del_ = del_;
        } else {
          result.del_ = delBuilder_.build();
        }
        if (allBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            all_ = java.util.Collections.unmodifiableList(all_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.all_ = all_;
        } else {
          result.all_ = allBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protos.Resources) {
          return mergeFrom((Protos.Resources)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protos.Resources other) {
        if (other == Protos.Resources.getDefaultInstance()) return this;
        if (addBuilder_ == null) {
          if (!other.add_.isEmpty()) {
            if (add_.isEmpty()) {
              add_ = other.add_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAddIsMutable();
              add_.addAll(other.add_);
            }
            onChanged();
          }
        } else {
          if (!other.add_.isEmpty()) {
            if (addBuilder_.isEmpty()) {
              addBuilder_.dispose();
              addBuilder_ = null;
              add_ = other.add_;
              bitField0_ = (bitField0_ & ~0x00000001);
              addBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddFieldBuilder() : null;
            } else {
              addBuilder_.addAllMessages(other.add_);
            }
          }
        }
        if (delBuilder_ == null) {
          if (!other.del_.isEmpty()) {
            if (del_.isEmpty()) {
              del_ = other.del_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDelIsMutable();
              del_.addAll(other.del_);
            }
            onChanged();
          }
        } else {
          if (!other.del_.isEmpty()) {
            if (delBuilder_.isEmpty()) {
              delBuilder_.dispose();
              delBuilder_ = null;
              del_ = other.del_;
              bitField0_ = (bitField0_ & ~0x00000002);
              delBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDelFieldBuilder() : null;
            } else {
              delBuilder_.addAllMessages(other.del_);
            }
          }
        }
        if (allBuilder_ == null) {
          if (!other.all_.isEmpty()) {
            if (all_.isEmpty()) {
              all_ = other.all_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAllIsMutable();
              all_.addAll(other.all_);
            }
            onChanged();
          }
        } else {
          if (!other.all_.isEmpty()) {
            if (allBuilder_.isEmpty()) {
              allBuilder_.dispose();
              allBuilder_ = null;
              all_ = other.all_;
              bitField0_ = (bitField0_ & ~0x00000004);
              allBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllFieldBuilder() : null;
            } else {
              allBuilder_.addAllMessages(other.all_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protos.Resources parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protos.Resources) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Resource> add_ =
        java.util.Collections.emptyList();
      private void ensureAddIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          add_ = new java.util.ArrayList<Resource>(add_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder> addBuilder_;

      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public java.util.List<Resource> getAddList() {
        if (addBuilder_ == null) {
          return java.util.Collections.unmodifiableList(add_);
        } else {
          return addBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public int getAddCount() {
        if (addBuilder_ == null) {
          return add_.size();
        } else {
          return addBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Protos.Resource getAdd(int index) {
        if (addBuilder_ == null) {
          return add_.get(index);
        } else {
          return addBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder setAdd(
          int index, Protos.Resource value) {
        if (addBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddIsMutable();
          add_.set(index, value);
          onChanged();
        } else {
          addBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder setAdd(
          int index, Protos.Resource.Builder builderForValue) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.set(index, builderForValue.build());
          onChanged();
        } else {
          addBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder addAdd(Protos.Resource value) {
        if (addBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddIsMutable();
          add_.add(value);
          onChanged();
        } else {
          addBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder addAdd(
          int index, Protos.Resource value) {
        if (addBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddIsMutable();
          add_.add(index, value);
          onChanged();
        } else {
          addBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder addAdd(
          Protos.Resource.Builder builderForValue) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.add(builderForValue.build());
          onChanged();
        } else {
          addBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder addAdd(
          int index, Protos.Resource.Builder builderForValue) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.add(index, builderForValue.build());
          onChanged();
        } else {
          addBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder addAllAdd(
          Iterable<? extends Resource> values) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, add_);
          onChanged();
        } else {
          addBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder clearAdd() {
        if (addBuilder_ == null) {
          add_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          addBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Builder removeAdd(int index) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.remove(index);
          onChanged();
        } else {
          addBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Protos.Resource.Builder getAddBuilder(
          int index) {
        return getAddFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Protos.ResourceOrBuilder getAddOrBuilder(
          int index) {
        if (addBuilder_ == null) {
          return add_.get(index);  } else {
          return addBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public java.util.List<? extends ResourceOrBuilder>
           getAddOrBuilderList() {
        if (addBuilder_ != null) {
          return addBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(add_);
        }
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Protos.Resource.Builder addAddBuilder() {
        return getAddFieldBuilder().addBuilder(
            Protos.Resource.getDefaultInstance());
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public Protos.Resource.Builder addAddBuilder(
          int index) {
        return getAddFieldBuilder().addBuilder(
            index, Protos.Resource.getDefaultInstance());
      }
      /**
       * <pre>
       * 添加的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Add = 1;</code>
       */
      public java.util.List<Resource.Builder>
           getAddBuilderList() {
        return getAddFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder>
          getAddFieldBuilder() {
        if (addBuilder_ == null) {
          addBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder>(
                  add_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          add_ = null;
        }
        return addBuilder_;
      }

      private java.util.List<Resource> del_ =
        java.util.Collections.emptyList();
      private void ensureDelIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          del_ = new java.util.ArrayList<Resource>(del_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder> delBuilder_;

      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public java.util.List<Resource> getDelList() {
        if (delBuilder_ == null) {
          return java.util.Collections.unmodifiableList(del_);
        } else {
          return delBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public int getDelCount() {
        if (delBuilder_ == null) {
          return del_.size();
        } else {
          return delBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Protos.Resource getDel(int index) {
        if (delBuilder_ == null) {
          return del_.get(index);
        } else {
          return delBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder setDel(
          int index, Protos.Resource value) {
        if (delBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDelIsMutable();
          del_.set(index, value);
          onChanged();
        } else {
          delBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder setDel(
          int index, Protos.Resource.Builder builderForValue) {
        if (delBuilder_ == null) {
          ensureDelIsMutable();
          del_.set(index, builderForValue.build());
          onChanged();
        } else {
          delBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder addDel(Protos.Resource value) {
        if (delBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDelIsMutable();
          del_.add(value);
          onChanged();
        } else {
          delBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder addDel(
          int index, Protos.Resource value) {
        if (delBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDelIsMutable();
          del_.add(index, value);
          onChanged();
        } else {
          delBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder addDel(
          Protos.Resource.Builder builderForValue) {
        if (delBuilder_ == null) {
          ensureDelIsMutable();
          del_.add(builderForValue.build());
          onChanged();
        } else {
          delBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder addDel(
          int index, Protos.Resource.Builder builderForValue) {
        if (delBuilder_ == null) {
          ensureDelIsMutable();
          del_.add(index, builderForValue.build());
          onChanged();
        } else {
          delBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder addAllDel(
          Iterable<? extends Resource> values) {
        if (delBuilder_ == null) {
          ensureDelIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, del_);
          onChanged();
        } else {
          delBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder clearDel() {
        if (delBuilder_ == null) {
          del_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          delBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Builder removeDel(int index) {
        if (delBuilder_ == null) {
          ensureDelIsMutable();
          del_.remove(index);
          onChanged();
        } else {
          delBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Protos.Resource.Builder getDelBuilder(
          int index) {
        return getDelFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Protos.ResourceOrBuilder getDelOrBuilder(
          int index) {
        if (delBuilder_ == null) {
          return del_.get(index);  } else {
          return delBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public java.util.List<? extends ResourceOrBuilder>
           getDelOrBuilderList() {
        if (delBuilder_ != null) {
          return delBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(del_);
        }
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Protos.Resource.Builder addDelBuilder() {
        return getDelFieldBuilder().addBuilder(
            Protos.Resource.getDefaultInstance());
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public Protos.Resource.Builder addDelBuilder(
          int index) {
        return getDelFieldBuilder().addBuilder(
            index, Protos.Resource.getDefaultInstance());
      }
      /**
       * <pre>
       * 减少的资源
       * </pre>
       *
       * <code>repeated .protos.Resource Del = 2;</code>
       */
      public java.util.List<Resource.Builder>
           getDelBuilderList() {
        return getDelFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder>
          getDelFieldBuilder() {
        if (delBuilder_ == null) {
          delBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder>(
                  del_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          del_ = null;
        }
        return delBuilder_;
      }

      private java.util.List<Resource> all_ =
        java.util.Collections.emptyList();
      private void ensureAllIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          all_ = new java.util.ArrayList<Resource>(all_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder> allBuilder_;

      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public java.util.List<Resource> getAllList() {
        if (allBuilder_ == null) {
          return java.util.Collections.unmodifiableList(all_);
        } else {
          return allBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public int getAllCount() {
        if (allBuilder_ == null) {
          return all_.size();
        } else {
          return allBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Protos.Resource getAll(int index) {
        if (allBuilder_ == null) {
          return all_.get(index);
        } else {
          return allBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder setAll(
          int index, Protos.Resource value) {
        if (allBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllIsMutable();
          all_.set(index, value);
          onChanged();
        } else {
          allBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder setAll(
          int index, Protos.Resource.Builder builderForValue) {
        if (allBuilder_ == null) {
          ensureAllIsMutable();
          all_.set(index, builderForValue.build());
          onChanged();
        } else {
          allBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder addAll(Protos.Resource value) {
        if (allBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllIsMutable();
          all_.add(value);
          onChanged();
        } else {
          allBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder addAll(
          int index, Protos.Resource value) {
        if (allBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllIsMutable();
          all_.add(index, value);
          onChanged();
        } else {
          allBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder addAll(
          Protos.Resource.Builder builderForValue) {
        if (allBuilder_ == null) {
          ensureAllIsMutable();
          all_.add(builderForValue.build());
          onChanged();
        } else {
          allBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder addAll(
          int index, Protos.Resource.Builder builderForValue) {
        if (allBuilder_ == null) {
          ensureAllIsMutable();
          all_.add(index, builderForValue.build());
          onChanged();
        } else {
          allBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder addAllAll(
          Iterable<? extends Resource> values) {
        if (allBuilder_ == null) {
          ensureAllIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, all_);
          onChanged();
        } else {
          allBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder clearAll() {
        if (allBuilder_ == null) {
          all_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          allBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Builder removeAll(int index) {
        if (allBuilder_ == null) {
          ensureAllIsMutable();
          all_.remove(index);
          onChanged();
        } else {
          allBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Protos.Resource.Builder getAllBuilder(
          int index) {
        return getAllFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Protos.ResourceOrBuilder getAllOrBuilder(
          int index) {
        if (allBuilder_ == null) {
          return all_.get(index);  } else {
          return allBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public java.util.List<? extends ResourceOrBuilder>
           getAllOrBuilderList() {
        if (allBuilder_ != null) {
          return allBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(all_);
        }
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Protos.Resource.Builder addAllBuilder() {
        return getAllFieldBuilder().addBuilder(
            Protos.Resource.getDefaultInstance());
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public Protos.Resource.Builder addAllBuilder(
          int index) {
        return getAllFieldBuilder().addBuilder(
            index, Protos.Resource.getDefaultInstance());
      }
      /**
       * <pre>
       * 总的资源
       * </pre>
       *
       * <code>repeated .protos.Resource All = 3;</code>
       */
      public java.util.List<Resource.Builder>
           getAllBuilderList() {
        return getAllFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder>
          getAllFieldBuilder() {
        if (allBuilder_ == null) {
          allBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Protos.Resource, Protos.Resource.Builder, Protos.ResourceOrBuilder>(
                  all_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          all_ = null;
        }
        return allBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.Resources)
    }

    // @@protoc_insertion_point(class_scope:protos.Resources)
    private static final Protos.Resources DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protos.Resources();
    }

    public static Protos.Resources getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Resources>
        PARSER = new com.google.protobuf.AbstractParser<Resources>() {
      @Override
      public Resources parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Resources(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Resources> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Resources> getParserForType() {
      return PARSER;
    }

    @Override
    public Protos.Resources getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_UserCache_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_UserCache_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Resource_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Resource_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Resources_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Resources_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014protos.proto\022\006protos\"A\n\tUserCache\022\013\n\003U" +
      "ID\030\001 \001(\r\022\014\n\004Name\030\002 \001(\t\022\014\n\004Head\030\003 \001(\005\022\013\n\003" +
      "VIP\030\004 \001(\005\"%\n\010Resource\022\014\n\004Type\030\001 \001(\005\022\013\n\003N" +
      "um\030\002 \001(\r\"h\n\tResources\022\035\n\003Add\030\001 \003(\0132\020.pro" +
      "tos.Resource\022\035\n\003Del\030\002 \003(\0132\020.protos.Resou" +
      "rce\022\035\n\003All\030\003 \003(\0132\020.protos.Resourceb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_UserCache_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_UserCache_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_UserCache_descriptor,
        new String[] { "UID", "Name", "Head", "VIP", });
    internal_static_protos_Resource_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Resource_descriptor,
        new String[] { "Type", "Num", });
    internal_static_protos_Resources_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_Resources_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Resources_descriptor,
        new String[] { "Add", "Del", "All", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
